module LetterDayCalendar exposing
    ( LetterDay
    , letterDayFromTime
    , letterDayImgInfo
    )

import Dict exposing (Dict)
import Time


type LetterDay
    = A
    | B
    | C
    | D
    | E
    | F
    | None


letterDayFromTime : Time.Zone -> Time.Posix -> LetterDay
letterDayFromTime zone posix =
    case Dict.get (dateKey zone posix) letterDayCalendar of
        Just letterDay ->
            letterDay

        Nothing ->
            None


letterDayImgInfo : LetterDay -> { src : String, alt : String }
letterDayImgInfo letterDay =
    case letterDay of
        A ->
            { src = "%PUBLIC_URL%/assets/images/penndale-letter-days-a.svg"
            , alt = "A Day"
            }

        B ->
            { src = "%PUBLIC_URL%/assets/images/penndale-letter-days-b.svg"
            , alt = "B Day"
            }

        C ->
            { src = "%PUBLIC_URL%/assets/images/penndale-letter-days-c.svg"
            , alt = "C Day"
            }

        D ->
            { src = "%PUBLIC_URL%/assets/images/penndale-letter-days-d.svg"
            , alt = "D Day"
            }

        E ->
            { src = "%PUBLIC_URL%/assets/images/penndale-letter-days-e.svg"
            , alt = "E Day"
            }

        F ->
            { src = "%PUBLIC_URL%/assets/images/penndale-letter-days-f.svg"
            , alt = "F Day"
            }

        None ->
            { src = "%PUBLIC_URL%/assets/images/penndale-letter-days-none.svg"
            , alt = "We're off today!"
            }



-- UTILS


{-| This is the format of the keys for the letter day calendar dict.
-}
dateKey : Time.Zone -> Time.Posix -> String
dateKey zone posix =
    let
        day =
            Time.toDay zone posix
                |> String.fromInt
                |> String.padLeft 2 '0'

        month =
            Time.toMonth zone posix
                |> toMonthNumber

        year =
            Time.toYear zone posix
                |> String.fromInt
    in
    -- E.g., 2020-10-20
    year ++ "-" ++ month ++ "-" ++ day


toMonthNumber : Time.Month -> String
toMonthNumber month =
    case month of
        Time.Jan ->
            "01"

        Time.Feb ->
            "02"

        Time.Mar ->
            "03"

        Time.Apr ->
            "04"

        Time.May ->
            "05"

        Time.Jun ->
            "06"

        Time.Jul ->
            "07"

        Time.Aug ->
            "08"

        Time.Sep ->
            "09"

        Time.Oct ->
            "10"

        Time.Nov ->
            "11"

        Time.Dec ->
            "12"


{-| DON'T EDIT DIRECTLY: Auto generated by the parse\_letter\_day\_calendar.rb
script.
-}
letterDayCalendar : Dict String LetterDay
letterDayCalendar =
    Dict.fromList
        [ ( "2020-11-04", A )
        , ( "2020-11-05", B )
        , ( "2020-11-06", C )
        , ( "2020-11-09", D )
        , ( "2020-11-10", E )
        , ( "2020-11-11", F )
        , ( "2020-11-12", A )
        , ( "2020-11-13", B )
        , ( "2020-11-16", C )
        , ( "2020-11-17", D )
        , ( "2020-11-18", E )
        , ( "2020-11-19", F )
        , ( "2020-11-20", A )
        , ( "2020-11-23", B )
        , ( "2020-11-24", C )
        , ( "2020-11-30", D )
        , ( "2020-12-01", E )
        , ( "2020-12-02", F )
        , ( "2020-12-03", A )
        , ( "2020-12-04", B )
        , ( "2020-12-07", C )
        , ( "2020-12-08", D )
        , ( "2020-12-09", E )
        , ( "2020-12-10", F )
        , ( "2020-12-11", A )
        , ( "2020-12-14", B )
        , ( "2020-12-15", C )
        , ( "2020-12-16", D )
        , ( "2020-12-18", E )
        , ( "2020-12-21", F )
        , ( "2020-12-22", A )
        , ( "2020-12-23", B )
        , ( "2021-01-04", C )
        , ( "2021-01-05", D )
        , ( "2021-01-06", E )
        , ( "2021-01-07", F )
        , ( "2021-01-08", A )
        , ( "2021-01-11", B )
        , ( "2021-01-12", C )
        , ( "2021-01-13", D )
        , ( "2021-01-14", E )
        , ( "2021-01-15", F )
        , ( "2021-01-19", A )
        , ( "2021-01-20", B )
        , ( "2021-01-21", C )
        , ( "2021-01-22", D )
        , ( "2021-01-25", E )
        , ( "2021-01-26", F )
        , ( "2021-01-27", A )
        , ( "2021-01-28", B )
        , ( "2021-01-29", C )
        , ( "2021-02-01", D )
        , ( "2021-02-02", E )
        , ( "2021-02-03", F )
        , ( "2021-02-04", A )
        , ( "2021-02-05", B )
        , ( "2021-02-08", C )
        , ( "2021-02-09", D )
        , ( "2021-02-10", E )
        , ( "2021-02-11", F )
        , ( "2021-02-16", A )
        , ( "2021-02-17", B )
        , ( "2021-02-18", C )
        , ( "2021-02-19", D )
        , ( "2021-02-22", E )
        , ( "2021-02-23", F )
        , ( "2021-02-24", A )
        , ( "2021-02-25", B )
        , ( "2021-02-26", C )
        , ( "2021-03-01", D )
        , ( "2021-03-02", E )
        , ( "2021-03-03", F )
        , ( "2021-03-04", A )
        , ( "2021-03-05", B )
        , ( "2021-03-08", C )
        , ( "2021-03-09", D )
        , ( "2021-03-10", E )
        , ( "2021-03-11", F )
        , ( "2021-03-12", A )
        , ( "2021-03-15", B )
        , ( "2021-03-16", C )
        , ( "2021-03-17", D )
        , ( "2021-03-18", E )
        , ( "2021-03-19", F )
        , ( "2021-03-22", A )
        , ( "2021-03-23", B )
        , ( "2021-03-24", C )
        , ( "2021-03-25", D )
        , ( "2021-03-26", E )
        , ( "2021-03-29", F )
        , ( "2021-03-30", A )
        , ( "2021-04-06", B )
        , ( "2021-04-07", C )
        , ( "2021-04-08", D )
        , ( "2021-04-09", E )
        , ( "2021-04-12", F )
        , ( "2021-04-13", A )
        , ( "2021-04-14", B )
        , ( "2021-04-15", C )
        , ( "2021-04-16", D )
        , ( "2021-04-19", E )
        , ( "2021-04-20", F )
        , ( "2021-04-21", A )
        , ( "2021-04-22", B )
        , ( "2021-04-23", C )
        , ( "2021-04-26", D )
        , ( "2021-04-27", E )
        , ( "2021-04-28", F )
        , ( "2021-04-29", A )
        , ( "2021-04-30", B )
        , ( "2021-05-03", C )
        , ( "2021-05-04", D )
        , ( "2021-05-05", E )
        , ( "2021-05-06", F )
        , ( "2021-05-07", A )
        , ( "2021-05-10", B )
        , ( "2021-05-11", C )
        , ( "2021-05-12", D )
        , ( "2021-05-13", E )
        , ( "2021-05-14", F )
        , ( "2021-05-17", A )
        , ( "2021-05-19", B )
        , ( "2021-05-20", C )
        , ( "2021-05-21", D )
        , ( "2021-05-24", E )
        , ( "2021-05-25", F )
        , ( "2021-05-26", A )
        , ( "2021-05-27", B )
        , ( "2021-05-28", C )
        , ( "2021-06-01", D )
        , ( "2021-06-02", E )
        , ( "2021-06-03", F )
        , ( "2021-06-04", A )
        , ( "2021-06-07", B )
        , ( "2021-06-08", C )
        , ( "2021-06-09", D )
        , ( "2021-06-10", E )
        ]
